# Generated by Django 3.0.3 on 2020-03-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weight', models.IntegerField()),
                ('price', models.IntegerField()),
                ('created_at', models.TextField()),
                ('updated_at', models.TextField()),
            ],
        ),
    ]
